/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import backend.AdminRole;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowEvent;

/**
 *
 * @author Menna Magdy
 */
public class AdminRoleWindow extends javax.swing.JFrame implements Node{

    private ViewEmployeesWindow viewEmployeesW;
    private AddEmployeeWindow addEmployeeW;
    private RemoveEmployeeWindow removeEmployeeW;
    private Node parent;
    private AdminRole admin; //Q: leh hena matenfa3sh tekoun default?

    /**
     * Creates new form AdminRoleWindow
     */
    public AdminRoleWindow() {
        initComponents();
        this.setTitle("Admin Role");
        admin = new AdminRole();
        try {
            String[][] tableData = null;
            tableData = new String[admin.getListOfEmployees().length][5];

            for (int i = 0; i < admin.getListOfEmployees().length; i++) {
                tableData[i] = admin.getListOfEmployees()[i].lineRepresentation().split(",");
            }

        }
        catch(NullPointerException e) {
            System.out.println("no admin fel role");
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        viewEmployeesButton = new javax.swing.JButton();
        addEmployeeButton = new javax.swing.JButton();
        removeEmployeeButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

//        addWindowListener(new java.awt.event.WindowAdapter() {
//            public void windowClosing(java.awt.event.WindowEvent evt) {
//                formWindowClosing(evt);
//            }
//        });

        viewEmployeesButton.setBackground(new java.awt.Color(51, 51, 51));
        viewEmployeesButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        viewEmployeesButton.setForeground(new java.awt.Color(255, 255, 255));
        viewEmployeesButton.setText("View Employees");
        viewEmployeesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmployeesButtonActionPerformed(evt);
            }
        });

        addEmployeeButton.setBackground(new java.awt.Color(51, 51, 51));
        addEmployeeButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        addEmployeeButton.setForeground(new java.awt.Color(255, 255, 255));
        addEmployeeButton.setText("Add Employee");
        addEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeButtonActionPerformed(evt);
            }
        });

        removeEmployeeButton.setBackground(new java.awt.Color(51, 51, 51));
        removeEmployeeButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        removeEmployeeButton.setForeground(new java.awt.Color(255, 255, 255));
        removeEmployeeButton.setText("Remove Employee");
        removeEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEmployeeButtonActionPerformed(evt);
            }
        });

        logoutButton.setBackground(new java.awt.Color(51, 51, 51));
        logoutButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Log Out");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(addEmployeeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(viewEmployeesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(removeEmployeeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                        .addComponent(logoutButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(viewEmployeesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(removeEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>


//    private void formWindowClosing(java.awt.event.WindowEvent evt) {
//        // TODO add your handling code here:
//        this.setVisible(false);
//
//    }

    private void viewEmployeesButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        viewEmployeesW = new ViewEmployeesWindow(this.admin);
        viewEmployeesW.setParentNode(this);

        this.setVisible(false);
        viewEmployeesW.setVisible(true);
    }

    private void addEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        addEmployeeW = new AddEmployeeWindow(this.admin);
        addEmployeeW.setParentNode(this);

        this.setVisible(false);
        addEmployeeW.setVisible(true);
    }

    private void removeEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        removeEmployeeW = new RemoveEmployeeWindow(this.admin);
        removeEmployeeW.setParentNode(this);

        this.setVisible(false);
        removeEmployeeW.setVisible(true);
    }

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        admin.logout();
//        // TODO add your handling code here:
        this.setVisible(false);
        ((JFrame)getParentNode().getParentNode()).setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRoleWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton addEmployeeButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton removeEmployeeButton;
    private javax.swing.JButton viewEmployeesButton;

    @Override
    public void setParentNode(Node node) {
        this.parent = node;
    }

    @Override
    public Node getParentNode() {
        return this.parent;
    }
    // End of variables declaration

}