package frontend;

import backend.*;

import javax.swing.JFrame;


public class EmployeeRoleWindow extends javax.swing.JFrame implements Node {

    private Node parent;
    private AddProductWindow addProduct;
    private ViewProductsWindow viewProducts;
    private PurchaseProductWindow purchaseProduct;
    private ViewPurchasedProductsWindow viewPurchaseProduct;
    private ReturnProductWindow returnProduct;
    
    private EmployeeRole employee;
 
    public EmployeeRoleWindow() {
        initComponents();
        employee = new EmployeeRole(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addProductButton = new javax.swing.JButton();
        viewProductsButton = new javax.swing.JButton();
        purchaseProductButton = new javax.swing.JButton();
        viewPurchaseProductsButton = new javax.swing.JButton();
        returnProductButton = new javax.swing.JButton();
        Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Employee Role");

        addProductButton.setBackground(new java.awt.Color(0, 0, 0));
        addProductButton.setForeground(new java.awt.Color(255, 255, 255));
        addProductButton.setText("Add Product");
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });

        viewProductsButton.setBackground(new java.awt.Color(0, 0, 0));
        viewProductsButton.setForeground(new java.awt.Color(255, 255, 255));
        viewProductsButton.setText("View Products");
        viewProductsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProductsButtonActionPerformed(evt);
            }
        });

        purchaseProductButton.setBackground(new java.awt.Color(0, 0, 0));
        purchaseProductButton.setForeground(new java.awt.Color(255, 255, 255));
        purchaseProductButton.setText("Purchase Product");
        purchaseProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseProductButtonActionPerformed(evt);
            }
        });

        viewPurchaseProductsButton.setBackground(new java.awt.Color(0, 0, 0));
        viewPurchaseProductsButton.setForeground(new java.awt.Color(255, 255, 255));
        viewPurchaseProductsButton.setText("View Purchased Products");
        viewPurchaseProductsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPurchaseProductsButtonActionPerformed(evt);
            }
        });

        returnProductButton.setBackground(new java.awt.Color(0, 0, 0));
        returnProductButton.setForeground(new java.awt.Color(255, 255, 255));
        returnProductButton.setText("Return Product");
        returnProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnProductButtonActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(0, 0, 0));
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewProductsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(purchaseProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewPurchaseProductsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(addProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewProductsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(purchaseProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewPurchaseProductsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(returnProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        employee.logout();
        this.setVisible(false);
        ((JFrame)getParentNode().getParentNode()).setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButtonActionPerformed
        // TODO add your handling code here:
        addProduct = new AddProductWindow(employee);
        this.setVisible(false);
        addProduct.setParentNode(this);
        addProduct.setVisible(true);
    }//GEN-LAST:event_addProductButtonActionPerformed

    private void viewProductsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProductsButtonActionPerformed
        // TODO add your handling code here:
         viewProducts = new ViewProductsWindow(employee);
        this.setVisible(false);
        viewProducts.setParentNode(this);
        viewProducts.setVisible(true);
    }//GEN-LAST:event_viewProductsButtonActionPerformed

    private void purchaseProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseProductButtonActionPerformed
        // TODO add your handling code here:
        purchaseProduct = new PurchaseProductWindow(employee);
        this.setVisible(false);
        purchaseProduct.setParentNode(this);
        purchaseProduct.setVisible(true);
    }//GEN-LAST:event_purchaseProductButtonActionPerformed

    private void returnProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnProductButtonActionPerformed
        // TODO add your handling code here:
        returnProduct = new ReturnProductWindow(employee);
        this.setVisible(false);
        returnProduct.setParentNode(this);
        returnProduct.setVisible(true);
    }//GEN-LAST:event_returnProductButtonActionPerformed

    private void viewPurchaseProductsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPurchaseProductsButtonActionPerformed
        // TODO add your handling code here:
        viewPurchaseProduct = new ViewPurchasedProductsWindow(employee);
        this.setVisible(false);
        viewPurchaseProduct.setParentNode(this);
        viewPurchaseProduct.setVisible(true);
    }//GEN-LAST:event_viewPurchaseProductsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeRoleWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeRoleWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton addProductButton;
    private javax.swing.JButton purchaseProductButton;
    private javax.swing.JButton returnProductButton;
    private javax.swing.JButton viewProductsButton;
    private javax.swing.JButton viewPurchaseProductsButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public Node getParentNode() {
        return this.parent;
    }

    @Override
    public void setParentNode(Node node) {
        this.parent = node;
    }
}
